---
services:
  postgres:
    container_name: postgres
    image: postgres:17.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=todos 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8008:80"
    depends_on:
      - "postgres"
    restart: unless-stopped
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: 4mirul/todo-client:latest
    container_name: client
    ports:
      - "3000:80"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: 4mirul/todo-server:latest
    ports:
      - "8001:8001"
    container_name: server
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - DB_HOST=postgres
    depends_on:
      - postgres
    command: ["sh", "-c", "sleep 10s && exec npm start"]
volumes:
  postgres_data:
networks:
  default:
    name: main-network